; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId= {{ "{{" }}{{AppInfo.AppId}}{{  "}" }}
; This script is designed to be installed as a single app targeting multiple Revit versions, but for the operation of separating apps for each Revit version, it temporarily takes the last version.
{% assign lastVersion = Versions | last %}
{% if lastVersion %}AppName={{ AppInfo.AppName }} for Revit {{ lastVersion.Name }}{% else %}AppName={{ AppInfo.AppName }}{% endif %}
AppVersion={{ AppInfo.AppVersion }}
;AppVerName={{ AppInfo.AppName }} {{ AppInfo.AppVersion }}
AppPublisher={{ AppInfo.AppPublisher }}
AppPublisherURL={{ AppInfo.AppUrl }}
AppSupportURL={{ AppInfo.AppUrl }}
AppUpdatesURL={{ AppInfo.AppUrl }}
DefaultDirName={autopf}\{{ AppInfo.AppName }}
DefaultGroupName={{ AppInfo.AppName }}
AppCopyright= {{ AppInfo.CopyRight }}
DisableDirPage=yes
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputBaseFilename={{ AppInfo.OutputFilename }}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile={{ AppInfo.CustomConfig.Icon }}
UninstallDisplayIcon={uninstallexe}
{% if AppInfo.IsIncludedLicense %}LicenseFile={{ AppInfo.AppLicenseTxt }}{% endif %}

[Types]
Name: "DLLInstall"; Description: "{{AppInfo.AppName}} for Revit {{ version.Name }} install";

[Components]{% for version in Versions %}
Name: "Revit{{ version.Name }}Dlls"; Description: "{{AppInfo.AppName}} for Revit {{ version.Name }}"; Types: DLLInstall;{% endfor %}

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Files]
{% if AppInfo.IsIncludedAppExe %}Source: "{{ AppInfo.AppExeName }}"; DestDir: "{app}"; Flags: ignoreversion{% endif %}
{% if AppInfo.IsIncludedLicense %}Source: "{{ AppInfo.AppLicenseTxt }}"; DestDir: "{app}"; Flags: ignoreversion{% endif %}
{% if AppInfo.IsIncludedManual %}Source: "{{ AppInfo.AppManualPdf }}"; DestDir: "{app}"; Flags: ignoreversion{% endif %}

Source: "{{ AppInfo.CustomConfig.CertTrustedPath }}{{ AppInfo.CustomConfig.CertTrustedName }}"; DestDir: "{app}"; Flags: ignoreversion;

; NOTE: Don't use "Flags: ignoreversion" on any shared system files
{% for version in Versions %}; Files of version {{ version.Name }}
{% for module in Modules %}
; Module {{ module.Name }}
Source: "{{ module.SrcPath }}{{ version.SourcePath }}{{ module.Name }}.addin"; DestDir: "{commonappdata}\Autodesk\Revit\Addins\{{ version.Name }}\"; Flags: ignoreversion; permissions:everyone-modify;  Components: Revit{{ version.Name }}Dlls
Source: "{{ module.SrcPath }}{{ version.SourcePath }}{{ module.Name }}.dll"; DestDir: "{commonappdata}\Autodesk\Revit\Addins\{{ version.Name }}\{{ module.DestPath }}"; Flags: ignoreversion; permissions:everyone-modify;  Components: Revit{{ version.Name }}Dlls
Source: "{{ module.SrcPath }}{{ version.SourcePath }}*.dll"; DestDir: "{commonappdata}\Autodesk\Revit\Addins\{{ version.Name }}\{{ module.DestPath }}"; Flags: ignoreversion; permissions:everyone-modify;  Components: Revit{{ version.Name }}Dlls
{% for resourceFolder in module.ResourceFolders[version.Name] %}
Source: "{{ module.SrcPath }}{{ version.SourcePath }}{{ resourceFolder }}*"; DestDir: "{commonappdata}\Autodesk\Revit\Addins\{{ version.Name }}\{{ module.DestPath }}{{ resourceFolder }}"; Flags: ignoreversion recursesubdirs createallsubdirs; permissions:everyone-modify; Components: Revit{{ version.Name }}Dlls{% endfor %}
;---
{% endfor %}; ./END version {{ version.Name }}

{% endfor %}

[Icons]
{% if AppInfo.IsIncludedAppExe %}Name: "{group}\Arent自動配筋DLLの情報"; Filename: "{app}\{{ AppInfo.AppExeName }}"{% endif %}
Name: "{group}\{cm:UninstallProgram,{{ AppInfo.AppName }}}"; Filename: "{uninstallexe}"
{% if AppInfo.IsIncludedLicense %}Name: "{group}\{{ AppInfo.AppLicenseName }}"; Filename: "{app}\{{ AppInfo.AppLicenseTxt }}"{% endif %}
{% if AppInfo.IsIncludedManual %}Name: "{group}\{{ AppInfo.AppManualName }}"; Filename: "{app}\{{ AppInfo.AppManualPdf }}" {% endif %}

[Run]
Filename: "certutil.exe"; Parameters: "-user -addstore TrustedPublisher ""{app}\{{ AppInfo.CustomConfig.CertTrustedName }}"""; StatusMsg: "Adding trusted publisher..."

[Code]
var
  { コンポーネント選択ページを表示したことを示す }
  initizliedComponentPage: Boolean;
{ コンポーネント選択ページのコンポーネントリストを走査して、
  システムのインストール済みのコンポーネントのチェックを外しておく }

{% for version in Versions %}
  var is{{ version.Name }}Installed: Boolean;
{% endfor %}
function CheckTargetDir(version: string): Boolean; forward;

procedure SelectDefaultComponents();
var
  idx: integer;
  compname: String;
begin
  // コンポーネントの選択ドロップダウンは非表示とする
  // (状況に応じて自動設定するため)
  WizardForm.TypesCombo.Visible := False;
  // コンポーネントリストの表示名を走査して、対象のコンポーネントを見つける。
  WizardForm.ComponentsList.Visible := True;
  for idx := 0 to WizardForm.ComponentsList.Items.Count - 1 do
  begin
    compname := WizardForm.ComponentsList.ItemCaption[idx];
    Log('Component Name: ' + compname);
    case compname of
{% for version in Versions %}
      '{{AppInfo.AppName}} for Revit {{ version.Name }}': begin
        if is{{ version.Name }}Installed then
          WizardForm.ComponentsList.Checked[idx] := True
        else
        begin
          // 非対応のコンポーネントはグレイアウトにする
          WizardForm.ComponentsList.Checked[idx] := False;
          WizardForm.ComponentsList.ItemEnabled[idx] := False;
        end;
      end;
{% endfor %}
    end;
  end;
end;
{ ページの切り替えごとに呼び出される }
procedure CurPageChanged(CurPageID: Integer);
begin
  case CurPageID of
    wpSelectComponents: begin
      if not initizliedComponentPage then begin
        SelectDefaultComponents();
        initizliedComponentPage := True;
      end;
    end;
  end;
end;

{ Nextボタンが押されたときに呼び出される }
function NextButtonClick(CurPageID: Integer): Boolean;
var
  idx: integer;
  compname: String;
begin
  Result := True;
  case CurPageID of
    wpSelectComponents: begin
      Result := False;
      for idx := 0 to WizardForm.ComponentsList.Items.Count - 1 do
      begin
        compname := WizardForm.ComponentsList.ItemCaption[idx];
        case compname of
{% for version in Versions %}
          '{{AppInfo.AppName}} for Revit {{ version.Name }}': begin
            if WizardForm.ComponentsList.Checked[idx] then begin
              Result := True;
            end;
          end;
{% endfor %}
        end;
      end;
      if(Result = False) then
      begin
        MsgBox('インストール先のRevitを選択してください', mbError, MB_OK);
      end;
    end;
  end;
end;

function IsAppRunning(const FileName : string): Boolean;
var
  FSWbemLocator: Variant;
  FWMIService   : Variant;
  FWbemObjectSet: Variant;
begin
  Result := false;
  try
    FSWbemLocator := CreateOleObject('WBEMScripting.SWBEMLocator');
    try
      FWMIService := FSWbemLocator.ConnectServer('', 'root\CIMV2', '', '');
      try
        FWbemObjectSet :=
          FWMIService.ExecQuery(
            Format('SELECT Name FROM Win32_Process Where Name="%s"', [FileName]));
        Result := (FWbemObjectSet.Count > 0);
      finally
        FWbemObjectSet := Unassigned;
      end;
    finally
      FWMIService := Unassigned;
    end;
  finally
    FSWbemLocator := Unassigned;
  end;
end;

function InitializeSetup(): Boolean;
begin
  // フォルダが存在しないとインストールするものがない
  Result := False;

  while IsAppRunning('Revit.exe') do
  begin
    MsgBox('Revitが動作中のためインストーラーを実行できません' + #13#10 + 'Revitを終了してからインストーラーを実行してください', mbError, MB_OK);
    begin
      Result := False
      Exit;
    end;
  end;

{% for version in Versions %}
  is{{ version.Name }}Installed := False;
{% endfor %}

{% for version in Versions %}
  if(CheckTargetDir('{{ version.Name }}')) then
  begin
    is{{ version.Name }}Installed := True
    Result := True;
  end;
{% endfor %}

  if(Result = False) then
  begin
    MsgBox('インストール先対象のRevitが見つかりません', mbError, MB_OK);
  end;
end;

function InitializeUninstall(): Boolean;
var
  Retry: Integer;
begin
  Result := False;

  if IsAppRunning('Revit.exe') then
  begin
    MsgBox('Revitが動作中のためアンインストーラーを実行できません' + #13#10 + 'Revitを終了してからアンインストーラーを実行してください', mbError, MB_OK);
    Exit;
  end;

  { OS 起動後初めてアンインストールを行う場合などに、DLL がロックされていて失敗する場合がある }
  { ディレクトリ情報へのアクセスにより簡易チェックし、失敗したら 1 秒待機して再試行 }
  for Retry := 1 to 3 do
  begin
    Log(Format('Uninstall pre-check attempt %d/%d', [Retry, 3]));

    Result := True;
{% for version in Versions %}
{% for module in Modules %}
    if not DirExists(ExpandConstant('{commonappdata}\Autodesk\Revit\Addins\{{ version.Name }}\{{ module.DestPath }}')) then
      Result := False;
{% endfor %}
{% endfor %}

    if Result then
      Exit;

    if Retry < 3 then
      Sleep(1000);
  end;

  MsgBox('アンインストールの準備が整いませんでした。' + #13#10 + 'しばらく待ってから再度実行してください。', mbError, MB_OK);
end;

function GetLastError() : LongInt;
 external 'GetLastError@kernel32.dll stdcall';

function CheckTargetDir(version: string): Boolean;
var
  targetPath: string;
  LastError: LongInt;
begin
  Result := false;
  targetPath := ExpandConstant('{commonappdata}\Autodesk\Revit\Addins\') + version;
  if(DirExists(targetPath)) then
  begin
    MsgBox('インストール先対象: Revit ' + version + #13#10 + targetPath + #13#10 +  'が見つかりました。', mbInformation, MB_OK);
    Result := True;
  end
  else
  begin
    LastError := GetLastError;
    Log(Format('Cannot get attributes of ' + targetPath + ': System Error. Code: %d. %s', [
          LastError, SysErrorMessage(LastError)]));
  end;
end;


