name: Implementation
description: 実装用のテンプレート / Template for Implementation
title: "[Implementation]"
body:
  - type: dropdown
    id: categories_classification
    attributes:
      label: Categories
      description: このタスクのCategoryを選択してください
      options:
        - Task
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 実装項目 / Implementation Items

  - type: textarea
    id: implementation-description
    attributes:
      label: 説明（テキスト）/ Description (Text)
      description: 実装項目を記載してください / Describe the implementation items
      value: |
        ## 実装項目 / 実装 Items
        - [ ] ...の画面作成
        - [ ] ...のロジック作成
        - [ ] ...のNUnitテスト作成

  - type: input
    id: acceptance-model
    attributes:
      label: 確認モデル / Verification Model
      description: 受け入れ基準を確認するモデルのGoogle Driveリンクを記載してください / Paste the Google Drive link for the verification model
      placeholder: https://drive.google.com/...

  - type: input
    id: target-release
    attributes:
      label: ブランチ or リリース対象 / Target Branch or Release
      description: 対象となるブランチやリリースを記載してください / Specify the target branch or release
      placeholder: https://github.com/ArentInc/kandenkou-revit-addin/...